spring:
  application:
    name: ms3-service
  profiles:
    active: rabbit # Mude aqui para 'kafka' quando quiser trocar o broker
  cloud:
    stream:
      function:
        definition: processAnalysis # Sua função Java