server:
  port: 8080

spring:
  application:
    name: gateway
  
  main:
    banner-mode: off
    web-application-type: reactive

  cloud:
    config:
      enabled: false
    
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      # ROTAS CONFIGURADAS MANUALMENTE
      routes:
        # Rota para o MS1
        - id: ms1
          uri: lb://ms1
          predicates:
            - Path=/ms1/**
          filters:
            - StripPrefix=1

        # Rota para o MS2 (Seu antigo MVC1IA?)
        - id: ms2
          uri: lb://ms2 # Nome exato que aparece no Eureka para o MS2
          predicates:
            - Path=/ms2/**
          filters:
            - StripPrefix=1

        # Rota para o MS3
        - id: ms3
          uri: lb://ms3
          predicates:
            - Path=/ms3/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    reactor.netty: DEBUG